version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tapp-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup/cloud-db.sql:/docker-entrypoint-initdb.d/cloud-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tapp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

